#!/bin/sh

ln -vs $PWD $HOME/rpmbuild

if [ -z $1 ]
then
 echo USAGE: $0 [FILE [FILE] ]
elif ls $*
then

 # main loop
 for file in $(echo $*)
 do
  if grep '.spec$\|.src.rpm$'<<<$file
  then
   echo "INFO: Rpmbuild is using $file as source."
   sudo dnf -y builddep $file
   echo status[$file]='n/a'
   grep '.spec$'<<<$file    && rpmbuild -ba $file       && status[$file]='OK'
   grep '.src.rpm$'<<<$file && rpmbuild --rebuild $file && status[$file]='OK'
  else
  echo "WARNING: $file not matches to mask. \*.spec or \*.src.rpm only allowed."
  fi
 done

else
 echo "WARNING: No source files found. Nothing to do"
fi

for file in $*
do
 echo "$file:	${status[$file]}"
done
