#!/bin/sh

ln -vs $PWD $HOME/rpmbuild
declare -A STATUS

if [ -z $1 ]
then
 echo USAGE: $0 [FILE [FILE] ]
elif ls $*
then

 # main loop
 for file in $(echo $*)
 do
  if grep '.spec$\|.src.rpm$'<<<$file
  then
   STATUS[$file]='n/a'
   echo "INFO: Rpmbuild is using $file as source."
   sudo dnf builddep -y $file
   grep '.spec$'<<<$file    && rpmbuild -ba $file       && STATUS[$file]='ok'
   grep '.src.rpm$'<<<$file && rpmbuild --rebuild $file && STATUS[$file]='ok'
  else
  echo "WARNING: $file not matches to mask. \*.spec or \*.src.rpm only allowed."
  fi
 done

else
 echo "WARNING: No source files found. Nothing to do"
fi

rm -rf $HOME/rpmbuild/BUILD*
chmod -R a+rw "$HOME/rpmbuild/"

for file in ${!STATUS[@]}
do
 echo "$file:	${STATUS[$file]}"
done